package com.nightonke.boommenu.b;

import android.content.Context;
import android.graphics.Color;
import android.graphics.Rect;
import android.graphics.Typeface;
import android.graphics.drawable.Drawable;
import android.text.TextUtils.TruncateAt;
import com.nightonke.boommenu.e;

public abstract class b {
    String A;
    String B;
    int C = -1;
    int D = -1;
    int E = -1;
    Rect F = new Rect(e.a(15.0f), e.a(52.0f), e.a(65.0f), e.a(72.0f));
    Rect G = new Rect(0, 0, 0, 0);
    Typeface H = null;
    int I = 1;
    int J = 17;
    TruncateAt K = TruncateAt.MARQUEE;
    int L = 10;
    int M = -1;
    int N = -1;
    int O = -1;
    String P;
    String Q;
    String R;
    int S = -1;
    int T = -1;
    int U = -1;
    Rect V = new Rect(e.a(70.0f), e.a(35.0f), e.a(280.0f), e.a(55.0f));
    Rect W = new Rect(0, 0, 0, 0);
    Typeface X = null;
    int Y = 1;
    int Z = 8388627;
    int a = -1;
    TruncateAt aa = TruncateAt.MARQUEE;
    int ab = 10;
    int ac = e.a(5.0f);
    int ad = e.a(80.0f);
    int ae = e.a(20.0f);
    boolean af = true;
    int ag = e.a();
    Integer ah = null;
    int ai = e.a();
    Integer aj = null;
    int ak = e.a();
    Integer al = null;
    boolean am = false;
    int an = e.a(40.0f);
    int ao = e.a(300.0f);
    int ap = e.a(60.0f);
    int aq = e.a(5.0f);
    g b;
    h c;
    boolean d = true;
    boolean e = true;
    boolean f = true;
    Integer g = null;
    Integer h = null;
    boolean i = true;
    int j = e.a(0.0f);
    int k = e.a(3.0f);
    int l = e.a(8.0f);
    int m = Color.parseColor("#88757575");
    int n = e.a(5.0f);
    int o = -1;
    int p = -1;
    int q = -1;
    Drawable r = null;
    Drawable s = null;
    Drawable t = null;
    Rect u = new Rect(e.a(10.0f), e.a(10.0f), e.a(70.0f), e.a(70.0f));
    Rect v = new Rect(0, 0, 0, 0);
    int w = -1;
    int x = -1;
    int y = -1;
    String z;

    public int a(Context context) {
        return (this.g == null && this.h == null) ? this.am ? e.a(context, this.al, this.ak) : e.a(context, this.ah, this.ag) : this.g == null ? e.b(context, this.h.intValue()) : e.a(context, this.h, this.g.intValue());
    }
}
