package at.grabner.circleprogress;

public final class R {

    public static final class attr {
        public static final int cpv_autoTextColor = 2130772243;
        public static final int cpv_autoTextSize = 2130772252;
        public static final int cpv_barColor = 2130772259;
        public static final int cpv_barColor1 = 2130772260;
        public static final int cpv_barColor2 = 2130772261;
        public static final int cpv_barColor3 = 2130772262;
        public static final int cpv_barStartEndLine = 2130772268;
        public static final int cpv_barStartEndLineColor = 2130772267;
        public static final int cpv_barStartEndLineSweep = 2130772266;
        public static final int cpv_barStartEndLineWidth = 2130772265;
        public static final int cpv_barStrokeCap = 2130772264;
        public static final int cpv_barWidth = 2130772258;
        public static final int cpv_blockCount = 2130772285;
        public static final int cpv_blockScale = 2130772284;
        public static final int cpv_decimalFormat = 2130772246;
        public static final int cpv_direction = 2130772253;
        public static final int cpv_fillColor = 2130772280;
        public static final int cpv_innerContourColor = 2130772278;
        public static final int cpv_innerContourSize = 2130772279;
        public static final int cpv_maxValue = 2130772255;
        public static final int cpv_maxValueAllowed = 2130772257;
        public static final int cpv_minValueAllowed = 2130772256;
        public static final int cpv_outerContourColor = 2130772276;
        public static final int cpv_outerContourSize = 2130772277;
        public static final int cpv_rimColor = 2130772274;
        public static final int cpv_rimWidth = 2130772275;
        public static final int cpv_roundToBlock = 2130772282;
        public static final int cpv_roundToWholeNumber = 2130772283;
        public static final int cpv_seekMode = 2130772281;
        public static final int cpv_showTextInSpinningMode = 2130772273;
        public static final int cpv_showUnit = 2130772242;
        public static final int cpv_spin = 2130772269;
        public static final int cpv_spinBarLength = 2130772272;
        public static final int cpv_spinColor = 2130772270;
        public static final int cpv_spinSpeed = 2130772271;
        public static final int cpv_startAngle = 2130772263;
        public static final int cpv_text = 2130772238;
        public static final int cpv_textColor = 2130772240;
        public static final int cpv_textMode = 2130772286;
        public static final int cpv_textScale = 2130772249;
        public static final int cpv_textSize = 2130772247;
        public static final int cpv_textTypeface = 2130772244;
        public static final int cpv_unit = 2130772239;
        public static final int cpv_unitColor = 2130772241;
        public static final int cpv_unitPosition = 2130772287;
        public static final int cpv_unitScale = 2130772250;
        public static final int cpv_unitSize = 2130772248;
        public static final int cpv_unitToTextScale = 2130772251;
        public static final int cpv_unitTypeface = 2130772245;
        public static final int cpv_value = 2130772254;
    }

    public static final class id {
        public static final int Both = 2131755196;
        public static final int Butt = 2131755193;
        public static final int CCW = 2131755191;
        public static final int CW = 2131755192;
        public static final int End = 2131755197;
        public static final int None = 2131755198;
        public static final int Percent = 2131755200;
        public static final int Round = 2131755194;
        public static final int Square = 2131755195;
        public static final int Start = 2131755199;
        public static final int Text = 2131755201;
        public static final int Value = 2131755202;
        public static final int bottom = 2131755203;
        public static final int left_bottom = 2131755204;
        public static final int left_top = 2131755205;
        public static final int right_bottom = 2131755206;
        public static final int right_top = 2131755207;
        public static final int top = 2131755208;
    }

    public static final class styleable {
        public static final int[] CircleProgressView = new int[]{com.fodlam.yds.R.attr.cpv_text, com.fodlam.yds.R.attr.cpv_unit, com.fodlam.yds.R.attr.cpv_textColor, com.fodlam.yds.R.attr.cpv_unitColor, com.fodlam.yds.R.attr.cpv_showUnit, com.fodlam.yds.R.attr.cpv_autoTextColor, com.fodlam.yds.R.attr.cpv_textTypeface, com.fodlam.yds.R.attr.cpv_unitTypeface, com.fodlam.yds.R.attr.cpv_decimalFormat, com.fodlam.yds.R.attr.cpv_textSize, com.fodlam.yds.R.attr.cpv_unitSize, com.fodlam.yds.R.attr.cpv_textScale, com.fodlam.yds.R.attr.cpv_unitScale, com.fodlam.yds.R.attr.cpv_unitToTextScale, com.fodlam.yds.R.attr.cpv_autoTextSize, com.fodlam.yds.R.attr.cpv_direction, com.fodlam.yds.R.attr.cpv_value, com.fodlam.yds.R.attr.cpv_maxValue, com.fodlam.yds.R.attr.cpv_minValueAllowed, com.fodlam.yds.R.attr.cpv_maxValueAllowed, com.fodlam.yds.R.attr.cpv_barWidth, com.fodlam.yds.R.attr.cpv_barColor, com.fodlam.yds.R.attr.cpv_barColor1, com.fodlam.yds.R.attr.cpv_barColor2, com.fodlam.yds.R.attr.cpv_barColor3, com.fodlam.yds.R.attr.cpv_startAngle, com.fodlam.yds.R.attr.cpv_barStrokeCap, com.fodlam.yds.R.attr.cpv_barStartEndLineWidth, com.fodlam.yds.R.attr.cpv_barStartEndLineSweep, com.fodlam.yds.R.attr.cpv_barStartEndLineColor, com.fodlam.yds.R.attr.cpv_barStartEndLine, com.fodlam.yds.R.attr.cpv_spin, com.fodlam.yds.R.attr.cpv_spinColor, com.fodlam.yds.R.attr.cpv_spinSpeed, com.fodlam.yds.R.attr.cpv_spinBarLength, com.fodlam.yds.R.attr.cpv_showTextInSpinningMode, com.fodlam.yds.R.attr.cpv_rimColor, com.fodlam.yds.R.attr.cpv_rimWidth, com.fodlam.yds.R.attr.cpv_outerContourColor, com.fodlam.yds.R.attr.cpv_outerContourSize, com.fodlam.yds.R.attr.cpv_innerContourColor, com.fodlam.yds.R.attr.cpv_innerContourSize, com.fodlam.yds.R.attr.cpv_fillColor, com.fodlam.yds.R.attr.cpv_seekMode, com.fodlam.yds.R.attr.cpv_roundToBlock, com.fodlam.yds.R.attr.cpv_roundToWholeNumber, com.fodlam.yds.R.attr.cpv_blockScale, com.fodlam.yds.R.attr.cpv_blockCount, com.fodlam.yds.R.attr.cpv_textMode, com.fodlam.yds.R.attr.cpv_unitPosition};
        public static final int CircleProgressView_cpv_autoTextColor = 5;
        public static final int CircleProgressView_cpv_autoTextSize = 14;
        public static final int CircleProgressView_cpv_barColor = 21;
        public static final int CircleProgressView_cpv_barColor1 = 22;
        public static final int CircleProgressView_cpv_barColor2 = 23;
        public static final int CircleProgressView_cpv_barColor3 = 24;
        public static final int CircleProgressView_cpv_barStartEndLine = 30;
        public static final int CircleProgressView_cpv_barStartEndLineColor = 29;
        public static final int CircleProgressView_cpv_barStartEndLineSweep = 28;
        public static final int CircleProgressView_cpv_barStartEndLineWidth = 27;
        public static final int CircleProgressView_cpv_barStrokeCap = 26;
        public static final int CircleProgressView_cpv_barWidth = 20;
        public static final int CircleProgressView_cpv_blockCount = 47;
        public static final int CircleProgressView_cpv_blockScale = 46;
        public static final int CircleProgressView_cpv_decimalFormat = 8;
        public static final int CircleProgressView_cpv_direction = 15;
        public static final int CircleProgressView_cpv_fillColor = 42;
        public static final int CircleProgressView_cpv_innerContourColor = 40;
        public static final int CircleProgressView_cpv_innerContourSize = 41;
        public static final int CircleProgressView_cpv_maxValue = 17;
        public static final int CircleProgressView_cpv_maxValueAllowed = 19;
        public static final int CircleProgressView_cpv_minValueAllowed = 18;
        public static final int CircleProgressView_cpv_outerContourColor = 38;
        public static final int CircleProgressView_cpv_outerContourSize = 39;
        public static final int CircleProgressView_cpv_rimColor = 36;
        public static final int CircleProgressView_cpv_rimWidth = 37;
        public static final int CircleProgressView_cpv_roundToBlock = 44;
        public static final int CircleProgressView_cpv_roundToWholeNumber = 45;
        public static final int CircleProgressView_cpv_seekMode = 43;
        public static final int CircleProgressView_cpv_showTextInSpinningMode = 35;
        public static final int CircleProgressView_cpv_showUnit = 4;
        public static final int CircleProgressView_cpv_spin = 31;
        public static final int CircleProgressView_cpv_spinBarLength = 34;
        public static final int CircleProgressView_cpv_spinColor = 32;
        public static final int CircleProgressView_cpv_spinSpeed = 33;
        public static final int CircleProgressView_cpv_startAngle = 25;
        public static final int CircleProgressView_cpv_text = 0;
        public static final int CircleProgressView_cpv_textColor = 2;
        public static final int CircleProgressView_cpv_textMode = 48;
        public static final int CircleProgressView_cpv_textScale = 11;
        public static final int CircleProgressView_cpv_textSize = 9;
        public static final int CircleProgressView_cpv_textTypeface = 6;
        public static final int CircleProgressView_cpv_unit = 1;
        public static final int CircleProgressView_cpv_unitColor = 3;
        public static final int CircleProgressView_cpv_unitPosition = 49;
        public static final int CircleProgressView_cpv_unitScale = 12;
        public static final int CircleProgressView_cpv_unitSize = 10;
        public static final int CircleProgressView_cpv_unitToTextScale = 13;
        public static final int CircleProgressView_cpv_unitTypeface = 7;
        public static final int CircleProgressView_cpv_value = 16;
    }
}
