package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

public final class PlayerColumnNames {
    public final String name;
    public final String title;
    public final String zzaPA;
    public final String zzaPB;
    public final String zzaPC;
    public final String zzaPD;
    public final String zzaPE;
    public final String zzaPF;
    public final String zzaPG;
    public final String zzaPH;
    public final String zzaPI;
    public final String zzaPJ;
    public final String zzaPK;
    public final String zzaPL;
    public final String zzaPM;
    public final String zzaPN;
    public final String zzaPO;
    public final String zzaPP;
    public final String zzaPQ;
    public final String zzaPR;
    public final String zzaPS;
    public final String zzaPm;
    public final String zzaPn;
    public final String zzaPo;
    public final String zzaPp;
    public final String zzaPq;
    public final String zzaPr;
    public final String zzaPs;
    public final String zzaPt;
    public final String zzaPu;
    public final String zzaPv;
    public final String zzaPw;
    public final String zzaPx;
    public final String zzaPy;
    public final String zzaPz;

    public PlayerColumnNames(String str) {
        if (TextUtils.isEmpty(str)) {
            this.zzaPm = "external_player_id";
            this.zzaPn = "profile_name";
            this.zzaPo = "profile_icon_image_uri";
            this.zzaPp = "profile_icon_image_url";
            this.zzaPq = "profile_hi_res_image_uri";
            this.zzaPr = "profile_hi_res_image_url";
            this.zzaPs = "last_updated";
            this.zzaPt = "is_in_circles";
            this.zzaPu = "played_with_timestamp";
            this.zzaPv = "current_xp_total";
            this.zzaPw = "current_level";
            this.zzaPx = "current_level_min_xp";
            this.zzaPy = "current_level_max_xp";
            this.zzaPz = "next_level";
            this.zzaPA = "next_level_max_xp";
            this.zzaPB = "last_level_up_timestamp";
            this.title = "player_title";
            this.zzaPC = "has_all_public_acls";
            this.zzaPD = "is_profile_visible";
            this.zzaPE = "most_recent_external_game_id";
            this.zzaPF = "most_recent_game_name";
            this.zzaPG = "most_recent_activity_timestamp";
            this.zzaPH = "most_recent_game_icon_uri";
            this.zzaPI = "most_recent_game_hi_res_uri";
            this.zzaPJ = "most_recent_game_featured_uri";
            this.zzaPK = "has_debug_access";
            this.zzaPL = "gamer_tag";
            this.name = "real_name";
            this.zzaPM = "banner_image_landscape_uri";
            this.zzaPN = "banner_image_landscape_url";
            this.zzaPO = "banner_image_portrait_uri";
            this.zzaPP = "banner_image_portrait_url";
            this.zzaPQ = "gamer_friend_status";
            this.zzaPR = "gamer_friend_update_timestamp";
            this.zzaPS = "is_muted";
            return;
        }
        String valueOf = String.valueOf(str);
        String valueOf2 = String.valueOf("external_player_id");
        this.zzaPm = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_name");
        this.zzaPn = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_icon_image_uri");
        this.zzaPo = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_icon_image_url");
        this.zzaPp = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_hi_res_image_uri");
        this.zzaPq = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("profile_hi_res_image_url");
        this.zzaPr = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("last_updated");
        this.zzaPs = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_in_circles");
        this.zzaPt = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("played_with_timestamp");
        this.zzaPu = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_xp_total");
        this.zzaPv = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level");
        this.zzaPw = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level_min_xp");
        this.zzaPx = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("current_level_max_xp");
        this.zzaPy = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("next_level");
        this.zzaPz = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("next_level_max_xp");
        this.zzaPA = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("last_level_up_timestamp");
        this.zzaPB = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("player_title");
        this.title = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("has_all_public_acls");
        this.zzaPC = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_profile_visible");
        this.zzaPD = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_external_game_id");
        this.zzaPE = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_name");
        this.zzaPF = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_activity_timestamp");
        this.zzaPG = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_icon_uri");
        this.zzaPH = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_hi_res_uri");
        this.zzaPI = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("most_recent_game_featured_uri");
        this.zzaPJ = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("has_debug_access");
        this.zzaPK = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_tag");
        this.zzaPL = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("real_name");
        this.name = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_landscape_uri");
        this.zzaPM = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_landscape_url");
        this.zzaPN = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_portrait_uri");
        this.zzaPO = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("banner_image_portrait_url");
        this.zzaPP = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_friend_status");
        this.zzaPQ = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("gamer_friend_update_timestamp");
        this.zzaPR = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
        valueOf = String.valueOf(str);
        valueOf2 = String.valueOf("is_muted");
        this.zzaPS = valueOf2.length() != 0 ? valueOf.concat(valueOf2) : new String(valueOf);
    }
}
